source 'https://rubygems.org'

ruby '2.2.0'
gem 'faker'
gem 'rails', '4.2.0'
gem 'bourbon'
gem 'neat'
gem 'pg'
gem 'devise'
gem 'paperclip', '~> 4.2'
gem 'aws-sdk', '< 2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'rails_12factor'
gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'puma'
gem 'fancybox2-rails', '~> 0.2.8'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'paper_trail', '~> 4.0.0.beta'
gem 'diffy'
gem 'commontator', '~> 4.10.0'
gem 'kaminari'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'pry-nav'
end
